#!/usr/bin/perl

# filename: lab01
#
# to execute:
# $ ./lab01 data

if (@ARGV eq 0) {
  print "\nUsage: ./lab01 <filename>\n";
  exit;
}

#  open data file for reading  
$filename = $ARGV[0];
if (!open(inf, $filename)) { 
   print "unable to open input file\n";
   exit;
}

while (<inf>)
{
  $line= $_;

  # the regex inside // matches lines that begin with an uppercase letter.
  # no other lines will be displayed.
  # the caret ^ marks the beginning of the line.
  # the $ marks the end of the line.
  # your job is to replace this regex with another one.
 
  if ($line =~ /^[A-Z].*$/ ) 
  {
     print "$line";
  }
  
}
close(inf); 
