#define YY_parser_h_included
/*#define YY_USE_CLASS 
*/
/*  A Bison++ parser, made from parse.y  */

 /* with Bison++ version bison++ Version 1.21.9-1, adapted from GNU bison by coetmeur@icdc.fr
Maintained by Magnus Ekdahl <magnus@debian.org>
  */


#line 1 "/usr/share/bison++/bison.cc"
/* -*-C-*-  Note some compilers choke on comments on `#line' lines.  */
/* Skeleton output parser for bison,
   Copyright (C) 1984, 1989, 1990 Bob Corbett and Richard Stallman

   This program is free software; you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation; either version 1, or (at your option)
   any later version.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with this program; if not, write to the Free Software
   Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.  

   As a special exception, when this file is copied by Bison++ into a
   Bison++ output file, you may use that output file without restriction.
   This special exception was added by the Free Software Foundation
   in version 1.24 of Bison, and has been in Bison++ since 1.21.9.  

*/

/* HEADER SECTION */
#if defined( _MSDOS ) || defined(MSDOS) || defined(__MSDOS__) 
 #define __MSDOS_AND_ALIKE
#endif

#if defined(_WINDOWS) && defined(_MSC_VER)
 #define __HAVE_NO_ALLOCA
 #define __MSDOS_AND_ALIKE
#endif

#ifndef alloca
 #if defined( __GNUC__)
  #define alloca __builtin_alloca

 #elif (!defined (__STDC__) && defined (sparc)) || defined (__sparc__) || defined (__sparc)  || defined (__sgi)
  #include <alloca.h>

 #elif defined (__MSDOS_AND_ALIKE)
  #include <malloc.h>
  #ifndef __TURBOC__
   /* MS C runtime lib */
   #define alloca _alloca
  #endif

 #elif defined(_AIX)
  /* pragma must be put before any C/C++ instruction !! */
  #pragma alloca
  #include <malloc.h>

 #elif defined(__hpux)
  #ifdef __cplusplus
   extern "C" {
     void *alloca (unsigned int);
   };
  #else /* not __cplusplus */
   void *alloca ();
  #endif /* not __cplusplus */

 #endif /* not _AIX  not MSDOS, or __TURBOC__ or _AIX, not sparc.  */
#endif /* alloca not defined.  */

#ifdef c_plusplus
 #ifndef __cplusplus
  #define __cplusplus
 #endif
#endif

#ifdef __cplusplus
 #ifndef YY_USE_CLASS
/*#warning "For C++ its recomended to use bison++, otherwise classes won't be generated"*/
 #endif
#else
 #ifndef __STDC__
  #define const
 #endif
 #ifdef YY_USE_CLASS
  #error "This is a C++ header generated by bison++, please use a C++ compiler!"
 #endif
#endif

#include <stdio.h>
#define YYBISON 1  

 #line 88 "/usr/share/bison++/bison.cc"
#line 4 "parse.y"


#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "symtab.h"
#include "defs.h"

#define TRUE 1
#define FALSE 0
#define MAXTOKENLEN 40
#define MAX_MSG_LEN 50
#define YYDEBUG 1

char errmsg[40];
int pflag = 0;   /* flag to let scanner know that parameters are coming */
int scope = 0;   /* parser sets this when entering param list scope */
extern int yylineno;
extern char *yytext;
FILE *logfd;
extern FILE *yyin;
extern FILE *yyout;
extern int yyparse();
int yydebug = 1;


#line 37 "parse.y"
typedef union { 
   int toktype;
   char *name;
} yy_parser_stype;
#define YY_parser_STYPE yy_parser_stype
#ifndef YY_USE_CLASS
#define YYSTYPE yy_parser_stype
#endif

#line 88 "/usr/share/bison++/bison.cc"
/* %{ and %header{ and %union, during decl */
#define YY_parser_BISON 1

#ifndef YY_parser_COMPATIBILITY
 #ifndef YY_USE_CLASS
  #define  YY_parser_COMPATIBILITY 1
 #else
  #define  YY_parser_COMPATIBILITY 0
 #endif
#endif

#if YY_parser_COMPATIBILITY != 0
 /* backward compatibility */
 #ifdef YYLTYPE
  #ifndef YY_parser_LTYPE
   #define YY_parser_LTYPE YYLTYPE
  #endif
 #endif
/* Testing alternative bison solution
   /#ifdef YYSTYPE*/
#ifndef YY_parser_STYPE 
   #define YY_parser_STYPE YYSTYPE
#endif
/*#endif*/
 #ifdef YYDEBUG
  #ifndef YY_parser_DEBUG
   #define  YY_parser_DEBUG YYDEBUG
  #endif
 #endif
 
 /* use goto to be compatible */
 #ifndef YY_parser_USE_GOTO
  #define YY_parser_USE_GOTO 1
 #endif
#endif

/* use no goto to be clean in C++ */
#ifndef YY_parser_USE_GOTO
 #define YY_parser_USE_GOTO 0
#endif

#ifndef YY_parser_PURE

 #line 130 "/usr/share/bison++/bison.cc"

#line 130 "/usr/share/bison++/bison.cc"
/*  YY_parser_PURE */
#endif

/* section apres lecture def, avant lecture grammaire S2 */

 #line 134 "/usr/share/bison++/bison.cc"

#line 134 "/usr/share/bison++/bison.cc"
/* prefix */
#ifndef YY_parser_DEBUG

 #line 136 "/usr/share/bison++/bison.cc"
#define YY_parser_DEBUG 1

#line 136 "/usr/share/bison++/bison.cc"
/* YY_parser_DEBUG */
#endif


#ifndef YY_parser_LSP_NEEDED

 #line 141 "/usr/share/bison++/bison.cc"

#line 141 "/usr/share/bison++/bison.cc"
 /* YY_parser_LSP_NEEDED*/
#endif



/* DEFAULT LTYPE*/
#ifdef YY_parser_LSP_NEEDED
#ifndef YY_parser_LTYPE
#ifndef BISON_YYLTYPE_ISDECLARED
#define BISON_YYLTYPE_ISDECLARED
typedef
  struct yyltype
    {
      int timestamp;
      int first_line;
      int first_column;
      int last_line;
      int last_column;
      char *text;
   }
  yyltype;

#endif
#define YY_parser_LTYPE yyltype
#endif
#endif
/* DEFAULT STYPE*/
      /* We used to use `unsigned long' as YY_parser_STYPE on MSDOS,
	 but it seems better to be consistent.
	 Most programs should declare their own type anyway.  */

#ifndef YY_parser_STYPE
#define YY_parser_STYPE int
#endif
/* DEFAULT MISCELANEOUS */
#ifndef YY_parser_PARSE
#define YY_parser_PARSE yyparse
#endif
#ifndef YY_parser_LEX
#define YY_parser_LEX yylex
#endif
#ifndef YY_parser_LVAL
#define YY_parser_LVAL yylval
#endif
#ifndef YY_parser_LLOC
#define YY_parser_LLOC yylloc
#endif
#ifndef YY_parser_CHAR
#define YY_parser_CHAR yychar
#endif
#ifndef YY_parser_NERRS
#define YY_parser_NERRS yynerrs
#endif
#ifndef YY_parser_DEBUG_FLAG
#define YY_parser_DEBUG_FLAG yydebug
#endif
#ifndef YY_parser_ERROR
#define YY_parser_ERROR yyerror
#endif

#ifndef YY_parser_PARSE_PARAM
 #ifndef YY_USE_CLASS
  #ifdef YYPARSE_PARAM
   #define YY_parser_PARSE_PARAM void* YYPARSE_PARAM 
  #else
   #ifndef __STDC__
    #ifndef __cplusplus
     #define YY_parser_PARSE_PARAM
    #endif
   #endif
  #endif
 #endif
 #ifndef YY_parser_PARSE_PARAM
  #define YY_parser_PARSE_PARAM void
 #endif
#endif

#if YY_parser_COMPATIBILITY != 0
/* backward compatibility */
#ifdef YY_parser_LTYPE
#ifndef YYLTYPE
#define YYLTYPE YY_parser_LTYPE
#else
/* WARNING obsolete !!! user defined YYLTYPE not reported into generated header */
#endif
#endif

/* Removed due to bison compabilityproblems
/#ifndef YYSTYPE
/#define YYSTYPE YY_parser_STYPE
/#else*/
/* WARNING obsolete !!! user defined YYSTYPE not reported into generated header */
/*#endif*/

#ifdef YY_parser_PURE
#  ifndef YYPURE
#    define YYPURE YY_parser_PURE
#  endif
#endif

#ifdef YY_parser_DEBUG
#  ifndef YYDEBUG
#    define YYDEBUG YY_parser_DEBUG 
#  endif
#endif

#ifndef YY_parser_ERROR_VERBOSE
 #ifdef YYERROR_VERBOSE
  #define YY_parser_ERROR_VERBOSE YYERROR_VERBOSE
 #endif
#endif

#ifndef YY_parser_LSP_NEEDED
#  ifdef YYLSP_NEEDED
#    define YY_parser_LSP_NEEDED YYLSP_NEEDED
#  endif
#endif

#endif

#ifndef YY_USE_CLASS
/* TOKEN C */

 #line 263 "/usr/share/bison++/bison.cc"
#define	IDENT	258
#define	ICONST	259
#define	FCONST	260
#define	CCONST	261
#define	SCONST	262
#define	INT	263
#define	FLOAT	264
#define	CHAR	265
#define	RET	266
#define	WHILE	267
#define	IF	268
#define	ELSE	269
#define	LPAREN	270
#define	RPAREN	271
#define	SEMI	272
#define	COMMA	273
#define	LBRACK	274
#define	RBRACK	275
#define	LCURLY	276
#define	RCURLY	277
#define	ASSIGN	278
#define	EQ	279
#define	LT	280
#define	LE	281
#define	GE	282
#define	GT	283
#define	NE	284
#define	PLUS	285
#define	MINUS	286
#define	TIMES	287
#define	OVER	288
#define	PLUSEQ	289
#define	MINUSEQ	290
#define	ERROR	291


#line 263 "/usr/share/bison++/bison.cc"
 /* #defines tokens */
#else
/* CLASS */
#ifndef YY_parser_CLASS
#define YY_parser_CLASS parser
#endif
#ifndef YY_parser_INHERIT
#define YY_parser_INHERIT
#endif
#ifndef YY_parser_MEMBERS
#define YY_parser_MEMBERS 
#endif
#ifndef YY_parser_LEX_BODY
#define YY_parser_LEX_BODY  
#endif
#ifndef YY_parser_ERROR_BODY
#define YY_parser_ERROR_BODY  
#endif
#ifndef YY_parser_CONSTRUCTOR_PARAM
#define YY_parser_CONSTRUCTOR_PARAM
#endif
#ifndef YY_parser_CONSTRUCTOR_CODE
#define YY_parser_CONSTRUCTOR_CODE
#endif
#ifndef YY_parser_CONSTRUCTOR_INIT
#define YY_parser_CONSTRUCTOR_INIT
#endif
/* choose between enum and const */
#ifndef YY_parser_USE_CONST_TOKEN
#define YY_parser_USE_CONST_TOKEN 0
/* yes enum is more compatible with flex,  */
/* so by default we use it */ 
#endif
#if YY_parser_USE_CONST_TOKEN != 0
#ifndef YY_parser_ENUM_TOKEN
#define YY_parser_ENUM_TOKEN yy_parser_enum_token
#endif
#endif

class YY_parser_CLASS YY_parser_INHERIT
{
public: 
#if YY_parser_USE_CONST_TOKEN != 0
/* static const int token ... */

 #line 307 "/usr/share/bison++/bison.cc"
static const int IDENT;
static const int ICONST;
static const int FCONST;
static const int CCONST;
static const int SCONST;
static const int INT;
static const int FLOAT;
static const int CHAR;
static const int RET;
static const int WHILE;
static const int IF;
static const int ELSE;
static const int LPAREN;
static const int RPAREN;
static const int SEMI;
static const int COMMA;
static const int LBRACK;
static const int RBRACK;
static const int LCURLY;
static const int RCURLY;
static const int ASSIGN;
static const int EQ;
static const int LT;
static const int LE;
static const int GE;
static const int GT;
static const int NE;
static const int PLUS;
static const int MINUS;
static const int TIMES;
static const int OVER;
static const int PLUSEQ;
static const int MINUSEQ;
static const int ERROR;


#line 307 "/usr/share/bison++/bison.cc"
 /* decl const */
#else
enum YY_parser_ENUM_TOKEN { YY_parser_NULL_TOKEN=0

 #line 310 "/usr/share/bison++/bison.cc"
	,IDENT=258
	,ICONST=259
	,FCONST=260
	,CCONST=261
	,SCONST=262
	,INT=263
	,FLOAT=264
	,CHAR=265
	,RET=266
	,WHILE=267
	,IF=268
	,ELSE=269
	,LPAREN=270
	,RPAREN=271
	,SEMI=272
	,COMMA=273
	,LBRACK=274
	,RBRACK=275
	,LCURLY=276
	,RCURLY=277
	,ASSIGN=278
	,EQ=279
	,LT=280
	,LE=281
	,GE=282
	,GT=283
	,NE=284
	,PLUS=285
	,MINUS=286
	,TIMES=287
	,OVER=288
	,PLUSEQ=289
	,MINUSEQ=290
	,ERROR=291


#line 310 "/usr/share/bison++/bison.cc"
 /* enum token */
     }; /* end of enum declaration */
#endif
public:
 int YY_parser_PARSE (YY_parser_PARSE_PARAM);
 virtual void YY_parser_ERROR(char *msg) YY_parser_ERROR_BODY;
#ifdef YY_parser_PURE
#ifdef YY_parser_LSP_NEEDED
 virtual int  YY_parser_LEX (YY_parser_STYPE *YY_parser_LVAL,YY_parser_LTYPE *YY_parser_LLOC) YY_parser_LEX_BODY;
#else
 virtual int  YY_parser_LEX (YY_parser_STYPE *YY_parser_LVAL) YY_parser_LEX_BODY;
#endif
#else
 virtual int YY_parser_LEX() YY_parser_LEX_BODY;
 YY_parser_STYPE YY_parser_LVAL;
#ifdef YY_parser_LSP_NEEDED
 YY_parser_LTYPE YY_parser_LLOC;
#endif
 int   YY_parser_NERRS;
 int    YY_parser_CHAR;
#endif
#if YY_parser_DEBUG != 0
 int YY_parser_DEBUG_FLAG;   /*  nonzero means print parse trace     */
#endif
public:
 YY_parser_CLASS(YY_parser_CONSTRUCTOR_PARAM);
public:
 YY_parser_MEMBERS 
};
/* other declare folow */
#if YY_parser_USE_CONST_TOKEN != 0

 #line 341 "/usr/share/bison++/bison.cc"
const int YY_parser_CLASS::IDENT=258;
const int YY_parser_CLASS::ICONST=259;
const int YY_parser_CLASS::FCONST=260;
const int YY_parser_CLASS::CCONST=261;
const int YY_parser_CLASS::SCONST=262;
const int YY_parser_CLASS::INT=263;
const int YY_parser_CLASS::FLOAT=264;
const int YY_parser_CLASS::CHAR=265;
const int YY_parser_CLASS::RET=266;
const int YY_parser_CLASS::WHILE=267;
const int YY_parser_CLASS::IF=268;
const int YY_parser_CLASS::ELSE=269;
const int YY_parser_CLASS::LPAREN=270;
const int YY_parser_CLASS::RPAREN=271;
const int YY_parser_CLASS::SEMI=272;
const int YY_parser_CLASS::COMMA=273;
const int YY_parser_CLASS::LBRACK=274;
const int YY_parser_CLASS::RBRACK=275;
const int YY_parser_CLASS::LCURLY=276;
const int YY_parser_CLASS::RCURLY=277;
const int YY_parser_CLASS::ASSIGN=278;
const int YY_parser_CLASS::EQ=279;
const int YY_parser_CLASS::LT=280;
const int YY_parser_CLASS::LE=281;
const int YY_parser_CLASS::GE=282;
const int YY_parser_CLASS::GT=283;
const int YY_parser_CLASS::NE=284;
const int YY_parser_CLASS::PLUS=285;
const int YY_parser_CLASS::MINUS=286;
const int YY_parser_CLASS::TIMES=287;
const int YY_parser_CLASS::OVER=288;
const int YY_parser_CLASS::PLUSEQ=289;
const int YY_parser_CLASS::MINUSEQ=290;
const int YY_parser_CLASS::ERROR=291;


#line 341 "/usr/share/bison++/bison.cc"
 /* const YY_parser_CLASS::token */
#endif
/*apres const  */
YY_parser_CLASS::YY_parser_CLASS(YY_parser_CONSTRUCTOR_PARAM) YY_parser_CONSTRUCTOR_INIT
{
#if YY_parser_DEBUG != 0
YY_parser_DEBUG_FLAG=0;
#endif
YY_parser_CONSTRUCTOR_CODE;
};
#endif

 #line 352 "/usr/share/bison++/bison.cc"


#define	YYFINAL		86
#define	YYFLAG		-32768
#define	YYNTBASE	37

#define YYTRANSLATE(x) ((unsigned)(x) <= 291 ? yytranslate[x] : 60)

static const char yytranslate[] = {     0,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     1,     2,     3,     4,     5,
     6,     7,     8,     9,    10,    11,    12,    13,    14,    15,
    16,    17,    18,    19,    20,    21,    22,    23,    24,    25,
    26,    27,    28,    29,    30,    31,    32,    33,    34,    35,
    36
};

#if YY_parser_DEBUG != 0
static const short yyprhs[] = {     0,
     0,     3,     4,     7,    11,    17,    19,    21,    23,    24,
    25,    26,    27,    43,    44,    46,    48,    52,    55,    59,
    61,    62,    65,    67,    69,    72,    74,    78,    84,    86,
    91,    95,    99,   101,   103,   105,   107,   109,   111,   115,
   117,   119,   121,   123,   125,   127,   129,   131,   133,   137,
   139,   141
};

static const short yyrhs[] = {    38,
    41,     0,     0,    38,    39,     0,    40,     3,    17,     0,
    40,     3,    23,    56,    17,     0,     8,     0,     9,     0,
    10,     0,     0,     0,     0,     0,    40,     3,    42,    15,
    43,    46,    16,    44,    21,    50,    11,    56,    45,    17,
    22,     0,     0,    47,     0,    48,     0,    48,    18,    47,
     0,    40,     3,     0,    21,    50,    22,     0,     1,     0,
     0,    50,    51,     0,     1,     0,    17,     0,    56,    17,
     0,    52,     0,    12,    53,    49,     0,    13,    53,    49,
    14,    49,     0,     1,     0,     3,    23,    56,    17,     0,
    15,    54,    16,     0,    58,    55,    58,     0,    24,     0,
    26,     0,    25,     0,    28,     0,    27,     0,    29,     0,
    56,    57,    58,     0,    58,     0,     1,     0,    32,     0,
    30,     0,    31,     0,    33,     0,    59,     0,     3,     0,
     6,     0,    15,    56,    16,     0,     4,     0,     5,     0,
     1,     0
};

#endif

#if (YY_parser_DEBUG != 0) || defined(YY_parser_ERROR_VERBOSE) 
static const short yyrline[] = { 0,
    61,    64,    65,    68,    71,    78,    79,    80,    83,    83,
    84,    85,    90,    93,    94,    97,    98,   101,   104,   105,
   109,   110,   111,   114,   115,   116,   117,   118,   119,   122,
   135,   138,   141,   141,   141,   141,   141,   141,   144,   157,
   158,   162,   162,   162,   162,   165,   166,   167,   168,   171,
   172,   173
};

static const char * const yytname[] = {   "$","error","$illegal.","IDENT","ICONST",
"FCONST","CCONST","SCONST","INT","FLOAT","CHAR","RET","WHILE","IF","ELSE","LPAREN",
"RPAREN","SEMI","COMMA","LBRACK","RBRACK","LCURLY","RCURLY","ASSIGN","EQ","LT",
"LE","GE","GT","NE","PLUS","MINUS","TIMES","OVER","PLUSEQ","MINUSEQ","ERROR",
"program","decl_seq","decl","type_spec","func","@1","@2","@3","@4","param_list",
"param_seq","param","block","stmt_seq","stmt","assign_stmt","condition","bool_expr",
"bool_op","expr","op","term","number",""
};
#endif

static const short yyr1[] = {     0,
    37,    38,    38,    39,    39,    40,    40,    40,    42,    43,
    44,    45,    41,    46,    46,    47,    47,    48,    49,    49,
    50,    50,    50,    51,    51,    51,    51,    51,    51,    52,
    53,    54,    55,    55,    55,    55,    55,    55,    56,    56,
    56,    57,    57,    57,    57,    58,    58,    58,    58,    59,
    59,    59
};

static const short yyr2[] = {     0,
     2,     0,     2,     3,     5,     1,     1,     1,     0,     0,
     0,     0,    15,     0,     1,     1,     3,     2,     3,     1,
     0,     2,     1,     1,     2,     1,     3,     5,     1,     4,
     3,     3,     1,     1,     1,     1,     1,     1,     3,     1,
     1,     1,     1,     1,     1,     1,     1,     1,     3,     1,
     1,     1
};

static const short yydefact[] = {     2,
     0,     6,     7,     8,     3,     0,     1,     9,     4,     0,
     0,    41,    47,    50,    51,    48,     0,     0,    40,    46,
    10,     0,     5,    43,    44,    42,    45,     0,    14,    49,
    52,    39,     0,     0,    15,    16,    18,    11,     0,     0,
    17,     0,    23,     0,    29,    47,     0,     0,     0,    24,
    22,    26,     0,     0,    12,     0,     0,     0,    25,     0,
     0,     0,     0,    20,     0,    27,     0,    30,     0,    31,
    33,    35,    34,    37,    36,    38,     0,     0,     0,    13,
    32,    19,    28,     0,     0,     0
};

static const short yydefgoto[] = {    84,
     1,     5,    33,     7,    11,    29,    40,    61,    34,    35,
    36,    66,    44,    51,    52,    57,    62,    77,    53,    28,
    19,    20
};

static const short yypact[] = {-32768,
     2,-32768,-32768,-32768,-32768,    12,-32768,    20,-32768,    16,
    10,-32768,-32768,-32768,-32768,-32768,    16,    33,-32768,-32768,
-32768,    23,-32768,-32768,-32768,-32768,-32768,   101,     2,-32768,
-32768,-32768,    24,    31,-32768,    18,-32768,-32768,     2,     5,
-32768,    56,-32768,    71,    87,    17,    16,    37,    37,-32768,
-32768,-32768,    61,    16,    91,   101,     8,     8,-32768,    68,
    41,    32,    84,-32768,     1,-32768,    65,-32768,    48,-32768,
-32768,-32768,-32768,-32768,-32768,-32768,   101,    29,     8,-32768,
-32768,-32768,-32768,    80,    81,-32768
};

static const short yypgoto[] = {-32768,
-32768,-32768,    86,-32768,-32768,-32768,-32768,-32768,-32768,    50,
-32768,   -55,    25,-32768,-32768,    46,-32768,-32768,    -9,-32768,
   -28,-32768
};


#define	YYLAST		124


static const short yytable[] = {    32,
    18,    43,    67,   -21,   -21,   -21,   -21,    22,    64,     2,
     3,     4,   -21,   -21,     8,   -21,    12,   -21,    13,    14,
    15,    16,   -21,    83,    21,    42,    37,    63,    65,    45,
    17,    46,    14,    15,    16,    39,     9,    55,    30,    54,
    48,    49,    10,    17,    60,    50,    38,    70,    81,    23,
    82,    56,    24,    25,    26,    27,    43,    69,   -21,   -21,
   -21,   -21,    24,    25,    26,    27,   -21,   -21,   -21,    80,
   -21,    45,   -21,    46,    14,    15,    16,    59,    79,    85,
    86,    47,    48,    49,    68,    17,     6,    50,    41,    78,
    24,    25,    26,    27,    58,     0,     0,    24,    25,    26,
    27,    31,     0,    13,    14,    15,    16,    71,    72,    73,
    74,    75,    76,     0,     0,    17,   -41,   -41,   -41,   -41,
    24,    25,    26,    27
};

static const short yycheck[] = {    28,
    10,     1,    58,     3,     4,     5,     6,    17,     1,     8,
     9,    10,    12,    13,     3,    15,     1,    17,     3,     4,
     5,     6,    22,    79,    15,    21,     3,    56,    21,     1,
    15,     3,     4,     5,     6,    18,    17,    47,    16,    23,
    12,    13,    23,    15,    54,    17,    16,    16,    77,    17,
    22,    15,    30,    31,    32,    33,     1,    17,     3,     4,
     5,     6,    30,    31,    32,    33,    11,    12,    13,    22,
    15,     1,    17,     3,     4,     5,     6,    17,    14,     0,
     0,    11,    12,    13,    17,    15,     1,    17,    39,    65,
    30,    31,    32,    33,    49,    -1,    -1,    30,    31,    32,
    33,     1,    -1,     3,     4,     5,     6,    24,    25,    26,
    27,    28,    29,    -1,    -1,    15,    30,    31,    32,    33,
    30,    31,    32,    33
};

#line 352 "/usr/share/bison++/bison.cc"
 /* fattrs + tables */

/* parser code folow  */


/* This is the parser code that is written into each bison parser
  when the %semantic_parser declaration is not specified in the grammar.
  It was written by Richard Stallman by simplifying the hairy parser
  used when %semantic_parser is specified.  */

/* Note: dollar marks section change
   the next  is replaced by the list of actions, each action
   as one case of the switch.  */ 

#if YY_parser_USE_GOTO != 0
/* 
 SUPRESSION OF GOTO : on some C++ compiler (sun c++)
  the goto is strictly forbidden if any constructor/destructor
  is used in the whole function (very stupid isn't it ?)
 so goto are to be replaced with a 'while/switch/case construct'
 here are the macro to keep some apparent compatibility
*/
#define YYGOTO(lb) {yy_gotostate=lb;continue;}
#define YYBEGINGOTO  enum yy_labels yy_gotostate=yygotostart; \
                     for(;;) switch(yy_gotostate) { case yygotostart: {
#define YYLABEL(lb) } case lb: {
#define YYENDGOTO } } 
#define YYBEGINDECLARELABEL enum yy_labels {yygotostart
#define YYDECLARELABEL(lb) ,lb
#define YYENDDECLARELABEL  };
#else
/* macro to keep goto */
#define YYGOTO(lb) goto lb
#define YYBEGINGOTO 
#define YYLABEL(lb) lb:
#define YYENDGOTO
#define YYBEGINDECLARELABEL 
#define YYDECLARELABEL(lb)
#define YYENDDECLARELABEL 
#endif
/* LABEL DECLARATION */
YYBEGINDECLARELABEL
  YYDECLARELABEL(yynewstate)
  YYDECLARELABEL(yybackup)
/* YYDECLARELABEL(yyresume) */
  YYDECLARELABEL(yydefault)
  YYDECLARELABEL(yyreduce)
  YYDECLARELABEL(yyerrlab)   /* here on detecting error */
  YYDECLARELABEL(yyerrlab1)   /* here on error raised explicitly by an action */
  YYDECLARELABEL(yyerrdefault)  /* current state does not do anything special for the error token. */
  YYDECLARELABEL(yyerrpop)   /* pop the current state because it cannot handle the error token */
  YYDECLARELABEL(yyerrhandle)  
YYENDDECLARELABEL
/* ALLOCA SIMULATION */
/* __HAVE_NO_ALLOCA */
#ifdef __HAVE_NO_ALLOCA
int __alloca_free_ptr(char *ptr,char *ref)
{if(ptr!=ref) free(ptr);
 return 0;}

#define __ALLOCA_alloca(size) malloc(size)
#define __ALLOCA_free(ptr,ref) __alloca_free_ptr((char *)ptr,(char *)ref)

#ifdef YY_parser_LSP_NEEDED
#define __ALLOCA_return(num) \
            do { return( __ALLOCA_free(yyss,yyssa)+\
		    __ALLOCA_free(yyvs,yyvsa)+\
		    __ALLOCA_free(yyls,yylsa)+\
		   (num)); } while(0)
#else
#define __ALLOCA_return(num) \
            do { return( __ALLOCA_free(yyss,yyssa)+\
		    __ALLOCA_free(yyvs,yyvsa)+\
		   (num)); } while(0)
#endif
#else
#define __ALLOCA_return(num) do { return(num); } while(0)
#define __ALLOCA_alloca(size) alloca(size)
#define __ALLOCA_free(ptr,ref) 
#endif

/* ENDALLOCA SIMULATION */

#define yyerrok         (yyerrstatus = 0)
#define yyclearin       (YY_parser_CHAR = YYEMPTY)
#define YYEMPTY         -2
#define YYEOF           0
#define YYACCEPT        __ALLOCA_return(0)
#define YYABORT         __ALLOCA_return(1)
#define YYERROR         YYGOTO(yyerrlab1)
/* Like YYERROR except do call yyerror.
   This remains here temporarily to ease the
   transition to the new meaning of YYERROR, for GCC.
   Once GCC version 2 has supplanted version 1, this can go.  */
#define YYFAIL          YYGOTO(yyerrlab)
#define YYRECOVERING()  (!!yyerrstatus)
#define YYBACKUP(token, value) \
do                                                              \
  if (YY_parser_CHAR == YYEMPTY && yylen == 1)                               \
    { YY_parser_CHAR = (token), YY_parser_LVAL = (value);                 \
      yychar1 = YYTRANSLATE (YY_parser_CHAR);                                \
      YYPOPSTACK;                                               \
      YYGOTO(yybackup);                                            \
    }                                                           \
  else                                                          \
    { YY_parser_ERROR ("syntax error: cannot back up"); YYERROR; }   \
while (0)

#define YYTERROR        1
#define YYERRCODE       256

#ifndef YY_parser_PURE
/* UNPURE */
#define YYLEX           YY_parser_LEX()
#ifndef YY_USE_CLASS
/* If nonreentrant, and not class , generate the variables here */
int     YY_parser_CHAR;                      /*  the lookahead symbol        */
YY_parser_STYPE      YY_parser_LVAL;              /*  the semantic value of the */
				/*  lookahead symbol    */
int YY_parser_NERRS;                 /*  number of parse errors so far */
#ifdef YY_parser_LSP_NEEDED
YY_parser_LTYPE YY_parser_LLOC;   /*  location data for the lookahead     */
			/*  symbol                              */
#endif
#endif


#else
/* PURE */
#ifdef YY_parser_LSP_NEEDED
#define YYLEX           YY_parser_LEX(&YY_parser_LVAL, &YY_parser_LLOC)
#else
#define YYLEX           YY_parser_LEX(&YY_parser_LVAL)
#endif
#endif
#ifndef YY_USE_CLASS
#if YY_parser_DEBUG != 0
int YY_parser_DEBUG_FLAG;                    /*  nonzero means print parse trace     */
/* Since this is uninitialized, it does not stop multiple parsers
   from coexisting.  */
#endif
#endif



/*  YYINITDEPTH indicates the initial size of the parser's stacks       */

#ifndef YYINITDEPTH
#define YYINITDEPTH 200
#endif

/*  YYMAXDEPTH is the maximum size the stacks can grow to
    (effective only if the built-in stack extension method is used).  */

#if YYMAXDEPTH == 0
#undef YYMAXDEPTH
#endif

#ifndef YYMAXDEPTH
#define YYMAXDEPTH 10000
#endif


#if __GNUC__ > 1                /* GNU C and GNU C++ define this.  */
#define __yy_bcopy(FROM,TO,COUNT)       __builtin_memcpy(TO,FROM,COUNT)
#else                           /* not GNU C or C++ */

/* This is the most reliable way to avoid incompatibilities
   in available built-in functions on various systems.  */

#ifdef __cplusplus
static void __yy_bcopy (char *from, char *to, int count)
#else
#ifdef __STDC__
static void __yy_bcopy (char *from, char *to, int count)
#else
static void __yy_bcopy (from, to, count)
     char *from;
     char *to;
     int count;
#endif
#endif
{
  register char *f = from;
  register char *t = to;
  register int i = count;

  while (i-- > 0)
    *t++ = *f++;
}
#endif


int
#ifdef YY_USE_CLASS
 YY_parser_CLASS::
#endif
     YY_parser_PARSE(YY_parser_PARSE_PARAM)
#ifndef __STDC__
#ifndef __cplusplus
#ifndef YY_USE_CLASS
/* parameter definition without protypes */
YY_parser_PARSE_PARAM_DEF
#endif
#endif
#endif
{
  register int yystate;
  register int yyn;
  register short *yyssp;
  register YY_parser_STYPE *yyvsp;
  int yyerrstatus;      /*  number of tokens to shift before error messages enabled */
  int yychar1=0;          /*  lookahead token as an internal (translated) token number */

  short yyssa[YYINITDEPTH];     /*  the state stack                     */
  YY_parser_STYPE yyvsa[YYINITDEPTH];        /*  the semantic value stack            */

  short *yyss = yyssa;          /*  refer to the stacks thru separate pointers */
  YY_parser_STYPE *yyvs = yyvsa;     /*  to allow yyoverflow to reallocate them elsewhere */

#ifdef YY_parser_LSP_NEEDED
  YY_parser_LTYPE yylsa[YYINITDEPTH];        /*  the location stack                  */
  YY_parser_LTYPE *yyls = yylsa;
  YY_parser_LTYPE *yylsp;

#define YYPOPSTACK   (yyvsp--, yyssp--, yylsp--)
#else
#define YYPOPSTACK   (yyvsp--, yyssp--)
#endif

  int yystacksize = YYINITDEPTH;

#ifdef YY_parser_PURE
  int YY_parser_CHAR;
  YY_parser_STYPE YY_parser_LVAL;
  int YY_parser_NERRS;
#ifdef YY_parser_LSP_NEEDED
  YY_parser_LTYPE YY_parser_LLOC;
#endif
#endif

  YY_parser_STYPE yyval;             /*  the variable used to return         */
				/*  semantic values from the action     */
				/*  routines                            */

  int yylen;
/* start loop, in which YYGOTO may be used. */
YYBEGINGOTO

#if YY_parser_DEBUG != 0
  if (YY_parser_DEBUG_FLAG)
    fprintf(stderr, "Starting parse\n");
#endif
  yystate = 0;
  yyerrstatus = 0;
  YY_parser_NERRS = 0;
  YY_parser_CHAR = YYEMPTY;          /* Cause a token to be read.  */

  /* Initialize stack pointers.
     Waste one element of value and location stack
     so that they stay on the same level as the state stack.
     The wasted elements are never initialized.  */

  yyssp = yyss - 1;
  yyvsp = yyvs;
#ifdef YY_parser_LSP_NEEDED
  yylsp = yyls;
#endif

/* Push a new state, which is found in  yystate  .  */
/* In all cases, when you get here, the value and location stacks
   have just been pushed. so pushing a state here evens the stacks.  */
YYLABEL(yynewstate)

  *++yyssp = yystate;

  if (yyssp >= yyss + yystacksize - 1)
    {
      /* Give user a chance to reallocate the stack */
      /* Use copies of these so that the &'s don't force the real ones into memory. */
      YY_parser_STYPE *yyvs1 = yyvs;
      short *yyss1 = yyss;
#ifdef YY_parser_LSP_NEEDED
      YY_parser_LTYPE *yyls1 = yyls;
#endif

      /* Get the current used size of the three stacks, in elements.  */
      int size = yyssp - yyss + 1;

#ifdef yyoverflow
      /* Each stack pointer address is followed by the size of
	 the data in use in that stack, in bytes.  */
#ifdef YY_parser_LSP_NEEDED
      /* This used to be a conditional around just the two extra args,
	 but that might be undefined if yyoverflow is a macro.  */
      yyoverflow("parser stack overflow",
		 &yyss1, size * sizeof (*yyssp),
		 &yyvs1, size * sizeof (*yyvsp),
		 &yyls1, size * sizeof (*yylsp),
		 &yystacksize);
#else
      yyoverflow("parser stack overflow",
		 &yyss1, size * sizeof (*yyssp),
		 &yyvs1, size * sizeof (*yyvsp),
		 &yystacksize);
#endif

      yyss = yyss1; yyvs = yyvs1;
#ifdef YY_parser_LSP_NEEDED
      yyls = yyls1;
#endif
#else /* no yyoverflow */
      /* Extend the stack our own way.  */
      if (yystacksize >= YYMAXDEPTH)
	{
	  YY_parser_ERROR("parser stack overflow");
	  __ALLOCA_return(2);
	}
      yystacksize *= 2;
      if (yystacksize > YYMAXDEPTH)
	yystacksize = YYMAXDEPTH;
      yyss = (short *) __ALLOCA_alloca (yystacksize * sizeof (*yyssp));
      __yy_bcopy ((char *)yyss1, (char *)yyss, size * sizeof (*yyssp));
      __ALLOCA_free(yyss1,yyssa);
      yyvs = (YY_parser_STYPE *) __ALLOCA_alloca (yystacksize * sizeof (*yyvsp));
      __yy_bcopy ((char *)yyvs1, (char *)yyvs, size * sizeof (*yyvsp));
      __ALLOCA_free(yyvs1,yyvsa);
#ifdef YY_parser_LSP_NEEDED
      yyls = (YY_parser_LTYPE *) __ALLOCA_alloca (yystacksize * sizeof (*yylsp));
      __yy_bcopy ((char *)yyls1, (char *)yyls, size * sizeof (*yylsp));
      __ALLOCA_free(yyls1,yylsa);
#endif
#endif /* no yyoverflow */

      yyssp = yyss + size - 1;
      yyvsp = yyvs + size - 1;
#ifdef YY_parser_LSP_NEEDED
      yylsp = yyls + size - 1;
#endif

#if YY_parser_DEBUG != 0
      if (YY_parser_DEBUG_FLAG)
	fprintf(stderr, "Stack size increased to %d\n", yystacksize);
#endif

      if (yyssp >= yyss + yystacksize - 1)
	YYABORT;
    }

#if YY_parser_DEBUG != 0
  if (YY_parser_DEBUG_FLAG)
    fprintf(stderr, "Entering state %d\n", yystate);
#endif

  YYGOTO(yybackup);
YYLABEL(yybackup)

/* Do appropriate processing given the current state.  */
/* Read a lookahead token if we need one and don't already have one.  */
/* YYLABEL(yyresume) */

  /* First try to decide what to do without reference to lookahead token.  */

  yyn = yypact[yystate];
  if (yyn == YYFLAG)
    YYGOTO(yydefault);

  /* Not known => get a lookahead token if don't already have one.  */

  /* yychar is either YYEMPTY or YYEOF
     or a valid token in external form.  */

  if (YY_parser_CHAR == YYEMPTY)
    {
#if YY_parser_DEBUG != 0
      if (YY_parser_DEBUG_FLAG)
	fprintf(stderr, "Reading a token: ");
#endif
      YY_parser_CHAR = YYLEX;
    }

  /* Convert token to internal form (in yychar1) for indexing tables with */

  if (YY_parser_CHAR <= 0)           /* This means end of input. */
    {
      yychar1 = 0;
      YY_parser_CHAR = YYEOF;                /* Don't call YYLEX any more */

#if YY_parser_DEBUG != 0
      if (YY_parser_DEBUG_FLAG)
	fprintf(stderr, "Now at end of input.\n");
#endif
    }
  else
    {
      yychar1 = YYTRANSLATE(YY_parser_CHAR);

#if YY_parser_DEBUG != 0
      if (YY_parser_DEBUG_FLAG)
	{
	  fprintf (stderr, "Next token is %d (%s", YY_parser_CHAR, yytname[yychar1]);
	  /* Give the individual parser a way to print the precise meaning
	     of a token, for further debugging info.  */
#ifdef YYPRINT
	  YYPRINT (stderr, YY_parser_CHAR, YY_parser_LVAL);
#endif
	  fprintf (stderr, ")\n");
	}
#endif
    }

  yyn += yychar1;
  if (yyn < 0 || yyn > YYLAST || yycheck[yyn] != yychar1)
    YYGOTO(yydefault);

  yyn = yytable[yyn];

  /* yyn is what to do for this token type in this state.
     Negative => reduce, -yyn is rule number.
     Positive => shift, yyn is new state.
       New state is final state => don't bother to shift,
       just return success.
     0, or most negative number => error.  */

  if (yyn < 0)
    {
      if (yyn == YYFLAG)
	YYGOTO(yyerrlab);
      yyn = -yyn;
      YYGOTO(yyreduce);
    }
  else if (yyn == 0)
    YYGOTO(yyerrlab);

  if (yyn == YYFINAL)
    YYACCEPT;

  /* Shift the lookahead token.  */

#if YY_parser_DEBUG != 0
  if (YY_parser_DEBUG_FLAG)
    fprintf(stderr, "Shifting token %d (%s), ", YY_parser_CHAR, yytname[yychar1]);
#endif

  /* Discard the token being shifted unless it is eof.  */
  if (YY_parser_CHAR != YYEOF)
    YY_parser_CHAR = YYEMPTY;

  *++yyvsp = YY_parser_LVAL;
#ifdef YY_parser_LSP_NEEDED
  *++yylsp = YY_parser_LLOC;
#endif

  /* count tokens shifted since error; after three, turn off error status.  */
  if (yyerrstatus) yyerrstatus--;

  yystate = yyn;
  YYGOTO(yynewstate);

/* Do the default action for the current state.  */
YYLABEL(yydefault)

  yyn = yydefact[yystate];
  if (yyn == 0)
    YYGOTO(yyerrlab);

/* Do a reduction.  yyn is the number of a rule to reduce with.  */
YYLABEL(yyreduce)
  yylen = yyr2[yyn];
  if (yylen > 0)
    yyval = yyvsp[1-yylen]; /* implement default value of the action */

#if YY_parser_DEBUG != 0
  if (YY_parser_DEBUG_FLAG)
    {
      int i;

      fprintf (stderr, "Reducing via rule %d (line %d), ",
	       yyn, yyrline[yyn]);

      /* Print the symbols being reduced, and their result.  */
      for (i = yyprhs[yyn]; yyrhs[i] > 0; i++)
	fprintf (stderr, "%s ", yytname[yyrhs[i]]);
      fprintf (stderr, " -> %s\n", yytname[yyr1[yyn]]);
    }
#endif


 #line 839 "/usr/share/bison++/bison.cc"

  switch (yyn) {

case 1:
#line 61 "parse.y"
{;;
    break;}
case 2:
#line 64 "parse.y"
{;;
    break;}
case 4:
#line 69 "parse.y"
{  setType (yyvsp[-1].name, yyvsp[-2].toktype); ;
    break;}
case 5:
#line 72 "parse.y"
{   setType (yyvsp[-3].name, yyvsp[-4].toktype); 
               if (yyvsp[-4].toktype != yyvsp[-1].toktype) 
             fprintf(logfd,"Type err type_spec assign_stmt,line %d\n",yylineno);
           ;
    break;}
case 6:
#line 78 "parse.y"
{yyval.toktype = ITYPE;;
    break;}
case 7:
#line 79 "parse.y"
{yyval.toktype = FTYPE; ;
    break;}
case 8:
#line 80 "parse.y"
{yyval.toktype = CTYPE;;
    break;}
case 9:
#line 83 "parse.y"
{scope++;;
    break;}
case 10:
#line 83 "parse.y"
{pflag++;;
    break;}
case 11:
#line 84 "parse.y"
{pflag--;;
    break;}
case 12:
#line 86 "parse.y"
{ setType(yyvsp[-10].name,yyvsp[-11].toktype); 
                 if (yyvsp[-11].toktype != yyvsp[0].toktype) 
                 fprintf(logfd,"Type err: return value, line %d\n",yylineno);
               ;
    break;}
case 14:
#line 93 "parse.y"
{;;
    break;}
case 15:
#line 94 "parse.y"
{;;
    break;}
case 16:
#line 97 "parse.y"
{ ;;
    break;}
case 18:
#line 102 "parse.y"
{  setType (yyvsp[0].name, yyvsp[-1].toktype); ;
    break;}
case 19:
#line 104 "parse.y"
{;;
    break;}
case 20:
#line 105 "parse.y"
{ yyerrok; return 0; ;
    break;}
case 21:
#line 109 "parse.y"
{ ;;
    break;}
case 22:
#line 110 "parse.y"
{;;
    break;}
case 23:
#line 111 "parse.y"
{ yyerrok; return 0;;
    break;}
case 24:
#line 114 "parse.y"
{ ; ;
    break;}
case 25:
#line 115 "parse.y"
{;;
    break;}
case 26:
#line 116 "parse.y"
{;;
    break;}
case 27:
#line 117 "parse.y"
{;;
    break;}
case 28:
#line 118 "parse.y"
{;;
    break;}
case 29:
#line 119 "parse.y"
{yyerrok; return 0;;
    break;}
case 30:
#line 123 "parse.y"
{ 
              /* check if rvalue has already violated type */
               if (yyvsp[-1].toktype == -1) 
                 yyval.toktype = yyvsp[-1].toktype;
               else {
                 int t = lookupType(yyvsp[-3].name); 
                 if (t != yyvsp[-1].toktype) 
                 fprintf(logfd,"Type err: assign_stmt, line %d\n",yylineno);
               }
            ;
    break;}
case 31:
#line 135 "parse.y"
{;;
    break;}
case 32:
#line 138 "parse.y"
{;;
    break;}
case 39:
#line 145 "parse.y"
{ 
              if (yyvsp[-2].toktype == yyvsp[0].toktype) /* no type error */
                   yyval.toktype = yyvsp[-2].toktype; 
              else
                 if (yyvsp[-2].toktype == -1) /* type error already found so trickle -1 up */
                     yyval.toktype = -1;
              else   /* we have an unreported type error */
              { 
                 yyval.toktype = -1;
                 fprintf(logfd,"Type err:exp->exp op term,line %d\n",yylineno);
              }
            ;
    break;}
case 40:
#line 157 "parse.y"
{ yyval.toktype = yyvsp[0].toktype; ;
    break;}
case 41:
#line 158 "parse.y"
{ yyerrok; return 0;;
    break;}
case 46:
#line 165 "parse.y"
{yyval.toktype = yyvsp[0].toktype;;
    break;}
case 47:
#line 166 "parse.y"
{yyval.toktype = lookupType(yyvsp[0].name); ;
    break;}
case 48:
#line 167 "parse.y"
{yyval.toktype = CTYPE; ;
    break;}
case 49:
#line 168 "parse.y"
{ yyval.toktype = yyvsp[-1].toktype; ;
    break;}
case 50:
#line 171 "parse.y"
{ yyval.toktype = ITYPE; ;
    break;}
case 51:
#line 172 "parse.y"
{ yyval.toktype = FTYPE; ;
    break;}
case 52:
#line 173 "parse.y"
{ yyerrok; return 0;;
    break;}
}

#line 839 "/usr/share/bison++/bison.cc"
   /* the action file gets copied in in place of this dollarsign  */
  yyvsp -= yylen;
  yyssp -= yylen;
#ifdef YY_parser_LSP_NEEDED
  yylsp -= yylen;
#endif

#if YY_parser_DEBUG != 0
  if (YY_parser_DEBUG_FLAG)
    {
      short *ssp1 = yyss - 1;
      fprintf (stderr, "state stack now");
      while (ssp1 != yyssp)
	fprintf (stderr, " %d", *++ssp1);
      fprintf (stderr, "\n");
    }
#endif

  *++yyvsp = yyval;

#ifdef YY_parser_LSP_NEEDED
  yylsp++;
  if (yylen == 0)
    {
      yylsp->first_line = YY_parser_LLOC.first_line;
      yylsp->first_column = YY_parser_LLOC.first_column;
      yylsp->last_line = (yylsp-1)->last_line;
      yylsp->last_column = (yylsp-1)->last_column;
      yylsp->text = 0;
    }
  else
    {
      yylsp->last_line = (yylsp+yylen-1)->last_line;
      yylsp->last_column = (yylsp+yylen-1)->last_column;
    }
#endif

  /* Now "shift" the result of the reduction.
     Determine what state that goes to,
     based on the state we popped back to
     and the rule number reduced by.  */

  yyn = yyr1[yyn];

  yystate = yypgoto[yyn - YYNTBASE] + *yyssp;
  if (yystate >= 0 && yystate <= YYLAST && yycheck[yystate] == *yyssp)
    yystate = yytable[yystate];
  else
    yystate = yydefgoto[yyn - YYNTBASE];

  YYGOTO(yynewstate);

YYLABEL(yyerrlab)   /* here on detecting error */

  if (! yyerrstatus)
    /* If not already recovering from an error, report this error.  */
    {
      ++YY_parser_NERRS;

#ifdef YY_parser_ERROR_VERBOSE
      yyn = yypact[yystate];

      if (yyn > YYFLAG && yyn < YYLAST)
	{
	  int size = 0;
	  char *msg;
	  int x, count;

	  count = 0;
	  /* Start X at -yyn if nec to avoid negative indexes in yycheck.  */
	  for (x = (yyn < 0 ? -yyn : 0);
	       x < (sizeof(yytname) / sizeof(char *)); x++)
	    if (yycheck[x + yyn] == x)
	      size += strlen(yytname[x]) + 15, count++;
	  msg = (char *) malloc(size + 15);
	  if (msg != 0)
	    {
	      strcpy(msg, "parse error");

	      if (count < 5)
		{
		  count = 0;
		  for (x = (yyn < 0 ? -yyn : 0);
		       x < (sizeof(yytname) / sizeof(char *)); x++)
		    if (yycheck[x + yyn] == x)
		      {
			strcat(msg, count == 0 ? ", expecting `" : " or `");
			strcat(msg, yytname[x]);
			strcat(msg, "'");
			count++;
		      }
		}
	      YY_parser_ERROR(msg);
	      free(msg);
	    }
	  else
	    YY_parser_ERROR ("parse error; also virtual memory exceeded");
	}
      else
#endif /* YY_parser_ERROR_VERBOSE */
	YY_parser_ERROR("parse error");
    }

  YYGOTO(yyerrlab1);
YYLABEL(yyerrlab1)   /* here on error raised explicitly by an action */

  if (yyerrstatus == 3)
    {
      /* if just tried and failed to reuse lookahead token after an error, discard it.  */

      /* return failure if at end of input */
      if (YY_parser_CHAR == YYEOF)
	YYABORT;

#if YY_parser_DEBUG != 0
      if (YY_parser_DEBUG_FLAG)
	fprintf(stderr, "Discarding token %d (%s).\n", YY_parser_CHAR, yytname[yychar1]);
#endif

      YY_parser_CHAR = YYEMPTY;
    }

  /* Else will try to reuse lookahead token
     after shifting the error token.  */

  yyerrstatus = 3;              /* Each real token shifted decrements this */

  YYGOTO(yyerrhandle);

YYLABEL(yyerrdefault)  /* current state does not do anything special for the error token. */

#if 0
  /* This is wrong; only states that explicitly want error tokens
     should shift them.  */
  yyn = yydefact[yystate];  /* If its default is to accept any token, ok.  Otherwise pop it.*/
  if (yyn) YYGOTO(yydefault);
#endif

YYLABEL(yyerrpop)   /* pop the current state because it cannot handle the error token */

  if (yyssp == yyss) YYABORT;
  yyvsp--;
  yystate = *--yyssp;
#ifdef YY_parser_LSP_NEEDED
  yylsp--;
#endif

#if YY_parser_DEBUG != 0
  if (YY_parser_DEBUG_FLAG)
    {
      short *ssp1 = yyss - 1;
      fprintf (stderr, "Error: state stack now");
      while (ssp1 != yyssp)
	fprintf (stderr, " %d", *++ssp1);
      fprintf (stderr, "\n");
    }
#endif

YYLABEL(yyerrhandle)

  yyn = yypact[yystate];
  if (yyn == YYFLAG)
    YYGOTO(yyerrdefault);

  yyn += YYTERROR;
  if (yyn < 0 || yyn > YYLAST || yycheck[yyn] != YYTERROR)
    YYGOTO(yyerrdefault);

  yyn = yytable[yyn];
  if (yyn < 0)
    {
      if (yyn == YYFLAG)
	YYGOTO(yyerrpop);
      yyn = -yyn;
      YYGOTO(yyreduce);
    }
  else if (yyn == 0)
    YYGOTO(yyerrpop);

  if (yyn == YYFINAL)
    YYACCEPT;

#if YY_parser_DEBUG != 0
  if (YY_parser_DEBUG_FLAG)
    fprintf(stderr, "Shifting error token, ");
#endif

  *++yyvsp = YY_parser_LVAL;
#ifdef YY_parser_LSP_NEEDED
  *++yylsp = YY_parser_LLOC;
#endif

  yystate = yyn;
  YYGOTO(yynewstate);
/* end loop, in which YYGOTO may be used. */
  YYENDGOTO
}

/* END */

 #line 1038 "/usr/share/bison++/bison.cc"
#line 176 "parse.y"



int main( int argc,char *argv[] )
{
   strcpy(errmsg,"type error\n");
   int i;
   if(argc < 2) {
      printf("Usage: cf <source filename>\n");
      exit(0);
   }
   FILE *fd = fopen(argv[1],"r");
   if (!fd) {
     printf("Unable to open file for reading\n");
     exit(0);
   }
   yyin = fd;

   logfd = fopen("log","w");
   if (!logfd) {
     printf("Unable to open log file for writing\n");
     exit(0);
   }


   fd = fopen("sym.dump","w");
   if (!fd) {
     printf("Unable to open file for writing\n");
     exit(0);
   }

   int flag = yyparse();
 
    /* dump symtab for debugging if necessary  */
    symtab_dump(fd);   

   /* cleanup */
   fclose(fd);
   fclose(logfd);
   fclose(yyin);

   return flag;
}


yywrap()
{
   return(1);
}

int yyerror(char * msg)
{ fprintf(logfd,"%s line %d.\n",msg,yylineno);
  return 0;
}
